import io
from typing import Union, List

import heapq
from collections import defaultdict

import cv2
import numpy as np
import requests
from PIL import Image
from math import pi, tan, cos, sin
from numpy import linalg as LA
from pathfinding.core.grid import Grid

from vlnce_baselines.map_navigation.map_utils import find_first_nonzero_elem_per_row, apply_color_to_map, \
    deduplicate_objects, get_ins2cat_dict
from vlnce_baselines.map_navigation.path_finding import PathFinder


class semantic_map_habitat_tools:
    """ class used to build semantic maps of the scenes.
    It takes dense observations of the environment and project pixels to the ground.
    """

    def __init__(self, saved_folder, MIN_DEPTH, MAX_DEPTH):
        from core import cfg

        self.scene_name = ''
        self.cell_size = cfg.SEM_MAP.CELL_SIZE
        self.step_size = 1000
        self.map_boundary = 5
        self.saved_folder = saved_folder

        self.MIN_DEPTH = MIN_DEPTH
        self.MAX_DEPTH = MAX_DEPTH

        # self.IGNORED_CLASS = [0, 1]  # ceiling class is ignored
        self.IGNORED_CLASS = []  # ceiling class is ignored

        # ==================================== initialize 4d grid =================================
        self.min_X = -cfg.SEM_MAP.WORLD_SIZE
        self.max_X = cfg.SEM_MAP.WORLD_SIZE
        self.min_Z = -cfg.SEM_MAP.WORLD_SIZE
        self.max_Z = cfg.SEM_MAP.WORLD_SIZE
        self.min_Y = 0.0
        self.max_Y = cfg.SENSOR.AGENT_HEIGHT + self.cell_size

        self.x_grid = np.arange(self.min_X, self.max_X, self.cell_size)
        self.z_grid = np.arange(self.min_Z, self.max_Z, self.cell_size)
        self.y_grid = np.arange(self.min_Y, self.max_Y, self.cell_size)

        self.THRESHOLD_HIGH = len(self.y_grid)

        self.four_dim_grid = np.zeros(
            (len(self.z_grid), len(self.y_grid) + 1,
             len(self.x_grid), 140),
            dtype=np.int16)  # x, y, z, C

        # self.occ_map = np.zeros((len(self.z_grid), len(self.x_grid)), dtype=np.int8)

        # ===================================
        self.H, self.W = len(self.z_grid), len(self.x_grid)
        self.min_x_coord = self.W - 1
        self.max_x_coord = 0
        self.min_z_coord = self.H - 1
        self.max_z_coord = 0
        self.max_y_coord = 0

        self.object_map = []  # {'position': (x, y, z), 'label': label, 'conf': conf}

    def detect(self, images: List[Union[str, np.ndarray, Image.Image]], server_url="http://127.0.0.1:5000/inference/"):
        def prepare_image(img: Union[str, np.ndarray, Image.Image]) -> bytes:
            if isinstance(img, str):
                image = Image.open(img).convert("RGB")
            elif isinstance(img, np.ndarray):
                image = Image.fromarray(img.astype(np.uint8)).convert("RGB")
            elif isinstance(img, Image.Image):
                image = img.convert("RGB")
            else:
                raise ValueError("不支持的图片类型")
            buf = io.BytesIO()
            image.save(buf, format="JPEG")
            return buf.getvalue()

        files = []
        results = []
        batch_size = 100
        for i in range(0, len(images), batch_size):
            batch_imgs = images[i:i + batch_size]
            batch_files = []
            for idx, img in enumerate(batch_imgs):
                img_bytes = prepare_image(img)
                batch_files.append(("images", (f"image{idx + i}.jpg", img_bytes, "image/jpeg")))
            response = requests.post(server_url, files=batch_files)
            response.raise_for_status()
            results.extend(response.json()['results'])
        return np.array(results)

    def convert_insseg_to_sseg(self, insseg, ins2cat_dict):
        """
        convert instance segmentation image InsSeg (generated by Habitat Simulator) into Semantic segmentation image SSeg,
        given the mapping from instance to category ins2cat_dict.
        """
        ins_id_list = list(ins2cat_dict.keys())
        sseg = np.zeros(insseg.shape, dtype=np.int16)
        for ins_id in ins_id_list:
            sseg = np.where(insseg == ins_id, ins2cat_dict[ins_id], sseg)
        return sseg

    def project_semantic_pixels_to_world_coords(self, sseg_img,
                                                current_depth,
                                                current_pose,
                                                gap=2,
                                                FOV=79,
                                                cx=320,
                                                cy=240,
                                                theta_x=0.0,
                                                resolution_x=640,
                                                resolution_y=480,
                                                ignored_classes=[],
                                                sensor_height=1.5):
        """
        Project pixels in sseg_img into world frame given depth image current_depth and camera pose current_pose.
        (u, v) = KRT(XYZ)
        """
        from core import cfg

        # camera intrinsic matrix
        radian = FOV * pi / 180.
        focal_length = cx / tan(radian / 2)
        K = np.array([[focal_length, 0, cx], [0, focal_length, cy], [0, 0, 1]])
        inv_K = LA.inv(K)
        # first compute the rotation and translation from current frame to goal frame
        # then compute the transformation matrix from goal frame to current frame
        # thransformation matrix is the camera2's extrinsic matrix
        tx, tz, theta = current_pose

        R_y = np.array([[cos(theta), 0, sin(theta)], [0, 1, 0],
                        [-sin(theta), 0, cos(theta)]])
        # used when I tilt the camera up/down
        R_x = np.array([[1, 0, 0], [0, cos(theta_x), -sin(theta_x)],
                        [0, sin(theta_x), cos(theta_x)]])
        R = R_y.dot(R_x)
        T = np.array([tx, 0, tz])
        transformation_matrix = np.empty((3, 4))
        transformation_matrix[:3, :3] = R
        transformation_matrix[:3, 3] = T

        # build the point matrix
        x = range(0, resolution_x, gap)
        y = range(0, resolution_y, gap)
        xv, yv = np.meshgrid(np.array(x), np.array(y))
        Z = current_depth[yv.flatten(), xv.flatten()].reshape(yv.shape[0], yv.shape[1])
        points_4d = np.ones((yv.shape[0], yv.shape[1], 4), np.float32)
        points_4d[:, :, 0] = xv
        points_4d[:, :, 1] = yv
        points_4d[:, :, 2] = Z
        points_4d = np.transpose(points_4d, (2, 0, 1)).reshape((4, -1))  # 4 x N

        # apply intrinsic matrix
        points_4d[[0, 1, 3], :] = inv_K.dot(points_4d[[0, 1, 3], :])
        points_4d[0, :] = points_4d[0, :] * points_4d[2, :]
        points_4d[1, :] = points_4d[1, :] * points_4d[2, :]

        # transform kp1_4d from camera1(current) frame to camera2(goal) frame through transformation matrix
        points_3d = transformation_matrix.dot(points_4d)

        # reverse y-dim and add sensor height
        points_3d[1, :] = points_3d[1, :] * -1 + sensor_height

        # ignore some artifacts points with depth == 0
        depth_points = current_depth[yv.flatten(), xv.flatten()].flatten()
        good = np.logical_and(depth_points > cfg.SENSOR.DEPTH_MIN,
                              depth_points < cfg.SENSOR.DEPTH_MAX)

        points_3d = points_3d[:, good]

        # pick x-row and z-row
        sseg_points = sseg_img[yv.flatten(), xv.flatten()].flatten()
        sseg_points = sseg_points[good]

        # ignore some classes points
        for c in ignored_classes:
            good = (sseg_points != c)
            sseg_points = sseg_points[good]
            points_3d = points_3d[:, good]

        return points_3d, sseg_points.astype(int)

    def project_pixels_to_world_coords(self, pixel_points: np.array, current_depth, current_pose, gap=2, FOV=79,
                                       cx=320,
                                       cy=240,
                                       theta_x=0.0,
                                       resolution_x=640,
                                       resolution_y=480,
                                       ignored_colors=[],
                                       sensor_height=1.5):
        from math import cos, sin, pi, tan
        import numpy.linalg as LA

        radian = FOV * pi / 180.
        focal_length = cx / tan(radian / 2)
        K = np.array([[focal_length, 0, cx], [0, focal_length, cy], [0, 0, 1]])
        inv_K = LA.inv(K)
        tx, tz, theta = current_pose

        R_y = np.array([[cos(theta), 0, sin(theta)], [0, 1, 0],
                        [-sin(theta), 0, cos(theta)]])
        R_x = np.array([[1, 0, 0], [0, cos(theta_x), -sin(theta_x)],
                        [0, sin(theta_x), cos(theta_x)]])
        R = R_y.dot(R_x)
        T = np.array([tx, 0, tz])
        transformation_matrix = np.empty((3, 4))
        transformation_matrix[:3, :3] = R
        transformation_matrix[:3, 3] = T

        # pixel_points: (N, 2), 每行是(u, v)
        u = pixel_points[:, 0]
        v = pixel_points[:, 1]
        Z = current_depth[v, u].flatten()  # 添加 .flatten() 确保是1D数组
        points_4d = np.ones((4, len(u)), np.float32)
        points_4d[0, :] = u
        points_4d[1, :] = v
        points_4d[2, :] = Z

        points_4d[[0, 1, 3], :] = inv_K.dot(points_4d[[0, 1, 3], :])
        points_4d[0, :] = points_4d[0, :] * points_4d[2, :]
        points_4d[1, :] = points_4d[1, :] * points_4d[2, :]

        points_3d = transformation_matrix.dot(points_4d)
        points_3d[1, :] = points_3d[1, :] * -1 + sensor_height

        depth_points = Z
        good = np.logical_and(depth_points > self.MIN_DEPTH,
                              depth_points < self.MAX_DEPTH)

        return points_3d, good

    def build_semantic_map(self, detect_results: List[dict], depth_img, insseg_img, pose, step_):
        """ update semantic map with observations rgb_img, depth_img, sseg_img and robot pose."""
        gap = 1
        resolution_x = 256

        map_pose = (pose[0], -pose[1], -pose[2])  # x, z, theta

        # sseg_img = self.convert_insseg_to_sseg(insseg_img, get_ins2cat_dict())
        sseg_img = insseg_img

        xyz_points, sseg_points = self.project_semantic_pixels_to_world_coords(
            sseg_img, depth_img, map_pose, gap=2, FOV=90, cx=128, cy=128, resolution_x=256, resolution_y=256,
            ignored_classes=self.IGNORED_CLASS)

        for detect_result in detect_results:
            center = [int((detect_result['xyxy'][0] + detect_result['xyxy'][2]) / 2),
                      int((detect_result['xyxy'][1] + detect_result['xyxy'][3]) / 2)]
            center = np.array([center])

            center_points, center_goods = self.project_pixels_to_world_coords(center, depth_img,
                                                                              map_pose, gap=gap, FOV=90,
                                                                              cx=128, cy=128,
                                                                              resolution_x=resolution_x,
                                                                              resolution_y=256)

            # if detect_result['cls'] not in ['picture']:
            #     continue

            self.object_map.append({
                'position': center_points[:3, 0],
                'label': detect_result['cls'],
                'conf': detect_result['conf']
            })

        mask_X = np.logical_and(xyz_points[0, :] > self.min_X,
                                xyz_points[0, :] < self.max_X)
        mask_Z = np.logical_and(xyz_points[2, :] > self.min_Z,
                                xyz_points[2, :] < self.max_Z)
        mask_XYZ = np.logical_and.reduce((mask_X, mask_Z))
        xyz_points = xyz_points[:, mask_XYZ]
        sseg_points = sseg_points[mask_XYZ]

        x_coord = np.floor(
            (xyz_points[0, :] - self.min_X) / self.cell_size).astype(int)
        y_coord = np.digitize(xyz_points[1, :], self.y_grid)
        z_coord = (self.H - 1) - np.floor(
            (xyz_points[2, :] - self.min_Z) / self.cell_size).astype(int)

        if x_coord.shape[0] > 0:
            self.four_dim_grid[z_coord, y_coord, x_coord, sseg_points] += 1

            # update the weights for the local map
            self.min_x_coord = min(max(np.min(x_coord) - self.map_boundary, 0),
                                   self.min_x_coord)
            self.max_x_coord = max(
                min(np.max(x_coord) + self.map_boundary, self.W - 1),
                self.max_x_coord)
            self.min_z_coord = min(max(np.min(z_coord) - self.map_boundary, 0),
                                   self.min_z_coord)
            self.max_z_coord = max(
                min(np.max(z_coord) + self.map_boundary, self.H - 1),
                self.max_z_coord)

            self.max_y_coord = max(np.max(y_coord), self.max_y_coord)

        if step_ % self.step_size == 0:
            self.get_semantic_map(step_)

    def build_semantic_map_fast(self, detect_results: List[dict], depth_img, insseg_img, pose, step_):
        """ 优化的语义地图构建函数 """
        gap = 1
        resolution_x = 256

        map_pose = (pose[0], -pose[1], -pose[2])  # x, z, theta

        sseg_img = self.convert_insseg_to_sseg(insseg_img, get_ins2cat_dict())
        # sseg_img = insseg_img

        # 1. 批量处理物体检测结果
        if detect_results:
            centers = np.array([[int((result['xyxy'][0] + result['xyxy'][2]) / 2),
                                 int((result['xyxy'][1] + result['xyxy'][3]) / 2)]
                                for result in detect_results])

            # 批量投影所有检测中心点
            center_points, center_goods = self.project_pixels_to_world_coords(
                centers, depth_img, map_pose, gap=gap, FOV=90,
                cx=128, cy=128, resolution_x=resolution_x, resolution_y=256)

            # 批量添加到物体地图
            valid_indices = np.where(center_goods)[0]
            for i in valid_indices:
                self.object_map.append({
                    'position': center_points[:3, i],
                    'label': detect_results[i]['cls'],
                    'conf': detect_results[i]['conf']
                })

        # 2. 语义点投影（保持原有逻辑）
        xyz_points, sseg_points = self.project_semantic_pixels_to_world_coords(
            sseg_img, depth_img, map_pose, gap=2, FOV=90, cx=128, cy=128,
            resolution_x=256, resolution_y=256, ignored_classes=self.IGNORED_CLASS)

        # 3. 优化边界检查 - 使用向量化操作
        mask_XYZ = ((xyz_points[0, :] > self.min_X) & (xyz_points[0, :] < self.max_X) &
                    (xyz_points[2, :] > self.min_Z) & (xyz_points[2, :] < self.max_Z))

        if not np.any(mask_XYZ):
            return  # 没有有效点，直接返回

        xyz_points = xyz_points[:, mask_XYZ]
        sseg_points = sseg_points[mask_XYZ]

        # 4. 批量坐标转换
        x_coord = ((xyz_points[0, :] - self.min_X) / self.cell_size).astype(int)
        y_coord = np.digitize(xyz_points[1, :], self.y_grid)
        z_coord = (self.H - 1) - ((xyz_points[2, :] - self.min_Z) / self.cell_size).astype(int)

        # 5. 使用numpy的高效累加
        if x_coord.shape[0] > 0:
            # 确保坐标在有效范围内
            valid_mask = ((x_coord >= 0) & (x_coord < self.W) &
                          (z_coord >= 0) & (z_coord < self.H) &
                          (y_coord >= 0) & (y_coord < len(self.y_grid) + 1))

            if np.any(valid_mask):
                x_coord = x_coord[valid_mask]
                y_coord = y_coord[valid_mask]
                z_coord = z_coord[valid_mask]
                sseg_points = sseg_points[valid_mask]

                # 使用numpy.add.at进行高效累加
                np.add.at(self.four_dim_grid, (z_coord, y_coord, x_coord, sseg_points), 1)

                # 6. 优化边界更新 - 减少函数调用
                x_min, x_max = np.min(x_coord), np.max(x_coord)
                z_min, z_max = np.min(z_coord), np.max(z_coord)

                self.min_x_coord = min(max(x_min - self.map_boundary, 0), self.min_x_coord)
                self.max_x_coord = max(min(x_max + self.map_boundary, self.W - 1), self.max_x_coord)
                self.min_z_coord = min(max(z_min - self.map_boundary, 0), self.min_z_coord)
                self.max_z_coord = max(min(z_max + self.map_boundary, self.H - 1), self.max_z_coord)
                self.max_y_coord = max(np.max(y_coord), self.max_y_coord)

        # 7. 条件检查地图保存
        if step_ % self.step_size == 0:
            self.get_semantic_map(step_)

    def get_semantic_map(self, step_):
        """ get the built semantic map. """
        smaller_four_dim_grid = self.four_dim_grid[self.min_z_coord:self.max_z_coord + 1, 0:self.THRESHOLD_HIGH,
                                self.min_x_coord:self.max_x_coord + 1, :]
        # argmax over the category axis
        zyx_grid = np.argmax(smaller_four_dim_grid, axis=3)
        # swap y dim to the last axis
        zxy_grid = np.swapaxes(zyx_grid, 1, 2)
        L, M, N = zxy_grid.shape
        zxy_grid = zxy_grid.reshape(L * M, N)

        semantic_map = find_first_nonzero_elem_per_row(zxy_grid)
        semantic_map = semantic_map.reshape(L, M)
        color_semantic_map = apply_color_to_map(semantic_map, dataset='ONEFORMER')

        if semantic_map.shape[0] > 0:
            self.save_sem_map_through_plt(
                color_semantic_map,
                f'{self.saved_folder}/step_{step_}_semantic.jpg')

    def save_sem_map_through_plt(self, img, name):
        """ save the figure img at directory 'name' using matplotlib"""
        # fig, ax = plt.subplots(nrows=1, ncols=1)
        # ax.imshow(img)
        # ax.get_xaxis().set_visible(False)
        # ax.get_yaxis().set_visible(False)
        # fig.tight_layout()
        # fig.savefig(name)
        # plt.close()
        cv2.imwrite(name, cv2.cvtColor(img, cv2.COLOR_RGB2BGR))

    def save_final_map(self, ENLARGE_SIZE=1, display_object_classes: list = None):
        """ save the built semantic map to a figure."""
        self.object_map = deduplicate_objects(self.object_map)

        smaller_four_dim_grid = self.four_dim_grid[self.min_z_coord:self.max_z_coord + 1, 0:self.THRESHOLD_HIGH,
                                self.min_x_coord:self.max_x_coord + 1, :]
        # argmax over the category axis
        zyx_grid = np.argmax(smaller_four_dim_grid, axis=3)
        # swap y dim to the last axis
        zxy_grid = np.swapaxes(zyx_grid, 1, 2)
        L, M, N = zxy_grid.shape
        zxy_grid = zxy_grid.reshape(L * M, N)

        semantic_map = find_first_nonzero_elem_per_row(zxy_grid)
        semantic_map = semantic_map.reshape(L, M)

        occ_map = np.zeros((L, M, 3), dtype=np.uint8)
        occ_map[semantic_map != 0] = (255, 255, 255)
        # for cls in [87, 122, 132]:
        #     occ_map[semantic_map == cls] = (255, 255, 255)
        # mask = (occ_map[:, :, 0] == 0) & (semantic_map != 0)
        # occ_map[mask] = (128, 128, 128)

        np.save(f'{self.saved_folder}/BEV_occ_map_raw.npy', occ_map)

        # save map v1
        # map_dict = {}
        # map_dict['min_x'] = self.min_x_coord
        # map_dict['max_x'] = self.max_x_coord
        # map_dict['min_z'] = self.min_z_coord
        # map_dict['max_z'] = self.max_z_coord
        # map_dict['min_X'] = self.min_X
        # map_dict['max_X'] = self.max_X
        # map_dict['min_Z'] = self.min_Z
        # map_dict['max_Z'] = self.max_Z
        # map_dict['W'] = self.W
        # map_dict['H'] = self.H
        # map_dict['semantic_map'] = semantic_map
        # print(f'semantic_map.shape = {semantic_map.shape}')
        # np.save(f'{self.saved_folder}/BEV_semantic_map.npy', map_dict)

        # save map v2
        self._save_complete_map()

        if ENLARGE_SIZE != 1:
            semantic_map = cv2.resize(
                semantic_map,
                (int(semantic_map.shape[1] * ENLARGE_SIZE),
                 int(semantic_map.shape[0] * ENLARGE_SIZE)),
                interpolation=cv2.INTER_NEAREST)
        color_semantic_map = apply_color_to_map(semantic_map, dataset='ONEFORMER')

        self.draw_objects_with_non_overlapping_labels(color_semantic_map, ENLARGE_SIZE,
                                                      display_object_classes=display_object_classes)

        self.save_sem_map_through_plt(color_semantic_map,
                                      f'{self.saved_folder}/final_semantic_map.jpg')

        self.save_sem_map_through_plt(occ_map,
                                      f'{self.saved_folder}/occ_map.jpg')

    def draw_objects_with_non_overlapping_labels(self, rgb_map, ENLARGE_SIZE=5, display_object_classes: list = None):
        """在地图上绘制物体，避免标签重叠"""
        drawn_labels = []  # 存储已绘制的标签位置和尺寸

        for obj in self.object_map:
            pos = obj['position']
            label = obj['label']
            conf = obj.get('conf', 1.0)

            if display_object_classes is not None and label not in display_object_classes:
                continue

            # 世界坐标转地图坐标
            x_map = int((pos[0] - self.min_X) / self.cell_size - self.min_x_coord) * ENLARGE_SIZE
            z_map = int((self.H - 1 - (pos[2] - self.min_Z) / self.cell_size) - self.min_z_coord) * ENLARGE_SIZE

            if 0 <= x_map < rgb_map.shape[1] and 0 <= z_map < rgb_map.shape[0]:
                # 绘制圆点
                cv2.circle(rgb_map, (x_map, z_map), 5 * ENLARGE_SIZE, (255, 0, 0), -1)

                # 计算文本尺寸
                # text = f"{label}({conf:.2f})"
                text = f"{label}"
                font_scale = 2
                # thickness = max(1, int(ENLARGE_SIZE)
                thickness = 2
                (text_w, text_h), baseline = cv2.getTextSize(text, cv2.FONT_HERSHEY_SIMPLEX, font_scale, thickness)

                # 寻找不重叠的文本位置
                text_pos = self._find_non_overlapping_position(
                    x_map, z_map, text_w, 10, drawn_labels, rgb_map.shape, ENLARGE_SIZE
                )
                # text_pos = (x_map + 3 * ENLARGE_SIZE, z_map - 3 * ENLARGE_SIZE)

                # 绘制文本
                cv2.putText(rgb_map, text, text_pos, cv2.FONT_HERSHEY_SIMPLEX,
                            font_scale, (255, 255, 255), thickness)

                # 记录已绘制的标签区域
                drawn_labels.append({
                    'x': text_pos[0],
                    'y': text_pos[1],
                    'w': text_w,
                    'h': text_h
                })

    def _find_non_overlapping_position(self, center_x, center_y, text_w, text_h, drawn_labels, map_shape, ENLARGE_SIZE):
        """寻找不重叠的文本位置（仅向下偏移）"""
        # 只向下偏移，避免左右偏移
        max_attempts = 10
        for i in range(max_attempts):
            offset_y = (i * (text_h)) * ENLARGE_SIZE
            candidate_x = center_x
            candidate_y = center_y + offset_y

            # 检查是否在地图范围内
            if (candidate_x < 0 or candidate_x + text_w >= map_shape[1] or
                    candidate_y - text_h < 0 or candidate_y >= map_shape[0]):
                continue

            # 检查是否与已有标签重叠
            overlap = False
            for drawn in drawn_labels:
                if self._rectangles_overlap(
                        candidate_x, candidate_y - text_h, text_w, text_h,
                        drawn['x'], drawn['y'] - drawn['h'], drawn['w'], drawn['h']
                ):
                    overlap = True
                    break

            if not overlap:
                return (candidate_x, candidate_y)

        # 如果都重叠，返回默认位置
        return (center_x, center_y + 10 * ENLARGE_SIZE)

    def _rectangles_overlap(self, x1, y1, w1, h1, x2, y2, w2, h2):
        """检查两个矩形是否重叠"""
        return not (x1 + w1 < x2 or x2 + w2 < x1 or y1 + h1 < y2 or y2 + h2 < y1)

    def _save_complete_map(self):
        """完整保存地图数据，包括所有必要信息用于后续加载"""
        smaller_four_dim_grid = self.four_dim_grid[self.min_z_coord:self.max_z_coord + 1, 0:self.THRESHOLD_HIGH,
                                self.min_x_coord:self.max_x_coord + 1, :]

        map_dict = {
            # 坐标边界信息
            'min_x_coord': self.min_x_coord,
            'max_x_coord': self.max_x_coord,
            'min_z_coord': self.min_z_coord,
            'max_z_coord': self.max_z_coord,
            'max_y_coord': self.max_y_coord,

            # 世界坐标系信息
            'min_X': self.min_X,
            'max_X': self.max_X,
            'min_Z': self.min_Z,
            'max_Z': self.max_Z,
            'min_Y': self.min_Y,
            'max_Y': self.max_Y,

            # 地图尺寸和参数
            'W': self.W,
            'H': self.H,
            'cell_size': self.cell_size,
            'THRESHOLD_HIGH': self.THRESHOLD_HIGH,

            # 网格信息
            'x_grid': self.x_grid,
            'z_grid': self.z_grid,
            'y_grid': self.y_grid,

            # 完整的四维网格数据
            'smaller_four_dim_grid': smaller_four_dim_grid,

            # 物体地图
            'object_map': self.object_map,

            # 其他参数
            'MIN_DEPTH': self.MIN_DEPTH,
            'MAX_DEPTH': self.MAX_DEPTH,
            'IGNORED_CLASS': self.IGNORED_CLASS,
            'scene_name': self.scene_name
        }

        np.save(f'{self.saved_folder}/BEV_semantic_map.npy', map_dict)
        print(f'完整地图数据已保存到 {self.saved_folder}/BEV_semantic_map.npy')

    def load_complete_map(self, map_file):
        """从文件加载完整的地图数据"""
        try:
            map_dict: dict = np.load(map_file, allow_pickle=True).item()

            # 恢复坐标边界信息
            self.min_x_coord = map_dict['min_x_coord']
            self.max_x_coord = map_dict['max_x_coord']
            self.min_z_coord = map_dict['min_z_coord']
            self.max_z_coord = map_dict['max_z_coord']
            self.max_y_coord = map_dict['max_y_coord']

            # 恢复世界坐标系信息
            self.min_X = map_dict['min_X']
            self.max_X = map_dict['max_X']
            self.min_Z = map_dict['min_Z']
            self.max_Z = map_dict['max_Z']
            self.min_Y = map_dict['min_Y']
            self.max_Y = map_dict['max_Y']

            # 恢复地图尺寸和参数
            self.W = map_dict['W']
            self.H = map_dict['H']
            self.cell_size = map_dict['cell_size']
            self.THRESHOLD_HIGH = map_dict['THRESHOLD_HIGH']

            # 恢复网格信息
            self.x_grid = map_dict['x_grid']
            self.z_grid = map_dict['z_grid']
            self.y_grid = map_dict['y_grid']

            # 重新初始化完整的四维网格
            self.four_dim_grid = np.zeros(
                (len(self.z_grid), len(self.y_grid) + 1,
                 len(self.x_grid), 140),
                dtype=np.int16)

            # 从smaller_four_dim_grid恢复数据到four_dim_grid
            smaller_four_dim_grid = map_dict['smaller_four_dim_grid']
            self.four_dim_grid[self.min_z_coord:self.max_z_coord + 1, 0:self.THRESHOLD_HIGH,
            self.min_x_coord:self.max_x_coord + 1, :] = smaller_four_dim_grid

            # 恢复物体地图
            self.object_map = map_dict['object_map']

            # 恢复其他参数
            self.MIN_DEPTH = map_dict['MIN_DEPTH']
            self.MAX_DEPTH = map_dict['MAX_DEPTH']
            self.IGNORED_CLASS = map_dict['IGNORED_CLASS']
            self.scene_name = map_dict['scene_name']

            print(f'完整地图数据已从 {map_file} 加载成功')
            return True

        except Exception as e:
            print(f'加载地图数据失败: {e}')
            return False

    def world_to_map_coords(self, world_position_3d):
        """
        将3维世界坐标转换为2维地图坐标

        Args:
            world_x (float): 世界坐标X
            world_y (float): 世界坐标Y (高度)
            world_z (float): 世界坐标Z

        Returns:
            tuple: (map_x, map_z, y_layer) 地图坐标x, z和对应的高度层
            如果坐标超出地图范围，返回 (None, None, None)
        """
        world_x, world_y, world_z = world_position_3d

        # 检查是否在世界坐标范围内
        if (world_x < self.min_X or world_x >= self.max_X or
                world_z < self.min_Z or world_z >= self.max_Z):
            return None, None, None

        # 转换为地图网格坐标
        map_x = int((world_x - self.min_X) / self.cell_size)
        map_z = (self.H - 1) - int((world_z - self.min_Z) / self.cell_size)
        y_layer = np.digitize(world_y, self.y_grid)

        # 检查是否在地图网格范围内
        if (map_x < 0 or map_x >= self.W or
                map_z < 0 or map_z >= self.H or
                y_layer < 0 or y_layer > len(self.y_grid)):
            return None, None, None

        return map_x, map_z, y_layer

    def map_to_world_coords(self, map_x, map_z, map_y=0):
        """
        将2维地图坐标转换为3维世界坐标

        Args:
            map_x (int): 地图坐标X
            map_z (int): 地图坐标Z
            map_y (int): 高度层索引，默认为0（地面）

        Returns:
            tuple: (world_x, world_y, world_z) 世界坐标
            如果坐标超出范围，返回 (None, None, None)
        """
        # 检查地图坐标是否有效
        if (map_x < 0 or map_x >= self.W or
                map_z < 0 or map_z >= self.H or
                map_y < 0 or map_y >= len(self.y_grid)):
            return None, None, None

        # 转换为世界坐标
        world_x = self.min_X + map_x * self.cell_size + self.cell_size / 2
        world_z = self.min_Z + (self.H - 1 - map_z) * self.cell_size + self.cell_size / 2
        world_y = self.y_grid[map_y] if map_y < len(self.y_grid) else self.y_grid[0]

        return world_x, world_y, world_z

    # def find_path_to(self, start_position_3d, goal_object: str):
    #     start_position = self.world_to_map_coords(start_position_3d)
    #     if start_position[0] is None:
    #         print("起始位置超出地图范围")
    #         return None
    #
    #     goal_object_list = [obj for obj in self.object_map if obj['label'] == goal_object]
    #     if not goal_object_list:
    #         print(f"地图中未找到目标物体: {goal_object}")
    #         return None
    #
    #     for goal_object in goal_object_list:
    #         goal_position = self.world_to_map_coords(goal_object['position'])
    #
    def convert_position_from_absolute_to_relative(self, absolute_position_map_2d):
        """
        将绝对地图坐标转换为相对于smaller_four_dim_grid的坐标
        Args:
            absolute_position_map_2d: (map_x, map_z) 绝对地图坐标
        Returns:
            tuple: (rel_x, rel_z) 相对smaller_four_dim_grid的坐标
            如果超出范围，返回(None, None)
        """
        map_x, map_z = absolute_position_map_2d
        rel_x = map_x - self.min_x_coord
        rel_z = map_z - self.min_z_coord
        if rel_x < 0 or rel_x >= (self.max_x_coord - self.min_x_coord + 1):
            return None, None
        if rel_z < 0 or rel_z >= (self.max_z_coord - self.min_z_coord + 1):
            return None, None
        return rel_x, rel_z

    def convert_position_from_relative_to_absolute(self, relative_position_2d):
        """
        将相对于smaller_four_dim_grid的坐标转换为绝对地图坐标
        Args:
            relative_position_2d: (rel_x, rel_z) 相对smaller_four_dim_grid的坐标
        Returns:
            tuple: (map_x, map_z) 绝对地图坐标
            如果超出范围，返回(None, None)
        """
        rel_x, rel_z = relative_position_2d
        map_x = rel_x + self.min_x_coord
        map_z = rel_z + self.min_z_coord
        if map_x < 0 or map_x >= self.W:
            return None, None
        if map_z < 0 or map_z >= self.H:
            return None, None
        return map_x, map_z


    def _generate_occupancy_map(self, occupancy_threshold=10):
        """
        生成2D占用地图，用于路径规划

        Args:
            occupancy_threshold: 占用判断阈值

        Returns:
            np.ndarray: 2D占用地图，1表示占用，0表示空闲
        """
        smaller_four_dim_grid = self.four_dim_grid[self.min_z_coord:self.max_z_coord + 1, 0:self.THRESHOLD_HIGH,
                                self.min_x_coord:self.max_x_coord + 1, :]
        # argmax over the category axis
        zyx_grid = np.argmax(smaller_four_dim_grid, axis=3)
        # swap y dim to the last axis
        zxy_grid = np.swapaxes(zyx_grid, 1, 2)
        L, M, N = zxy_grid.shape
        zxy_grid = zxy_grid.reshape(L * M, N)

        semantic_map = find_first_nonzero_elem_per_row(zxy_grid)
        semantic_map = semantic_map.reshape(L, M)

        occ_map = np.zeros((L, M), dtype=np.uint8)
        # occ_map[np.logical_or.reduce((semantic_map == 87, semantic_map == 122, semantic_map == 132))] = 1
        for cls in [87, 122, 132]:
            occ_map[semantic_map == cls] = 1
        # mask = (occ_map[:, :, 0] == 0) & (semantic_map != 0)
        # occ_map[mask] = (128, 128, 128)
        # occ_map[semantic_map != 0] = 1
        return occ_map

    def find_path_to_area_around_object(self, start_position_3d, goal_object: str, search_radius=5):
        """
        使用A*算法寻找从起始位置到目标物体周围区域的最优路径

        Args:
            start_position_3d: 起始位置的3D世界坐标 (x, y, z)
            goal_object: 目标物体的类别名称
            search_radius: 搜索半径，向外扩展的格子数

        Returns:
            dict: 包含路径信息的字典，如果无法到达返回None
        """
        start_position = self.world_to_map_coords(start_position_3d)
        start_position = self.convert_position_from_absolute_to_relative(start_position[:2])
        if start_position[0] is None:
            print("起始位置超出地图范围")
            return None

        goal_object_list = [obj for obj in self.object_map if obj['label'] == goal_object]
        if not goal_object_list:
            print(f"地图中未找到目标物体: {goal_object}")
            return None

        # 生成占用地图
        occ_map = self._generate_occupancy_map()
        occ_map_grid = Grid(matrix=occ_map)
        path_finder = PathFinder(tolerance=search_radius)

        best_result = None
        shortest_distance = float('inf')

        for goal_obj in goal_object_list:
            goal_center = self.world_to_map_coords(goal_obj['position'])
            goal_center = self.convert_position_from_absolute_to_relative(goal_center[:2])

            if goal_center[0] is None:
                continue

            start = [start_position[0], start_position[1]]
            goal = [goal_center[0], goal_center[1]]
            path, _ = path_finder.astar(start, goal, occ_map_grid)

            if path:
                path_length = len(path)
                if path_length < shortest_distance:
                    shortest_distance = path_length
                    best_result = {
                        # 'path': [self.convert_position_from_relative_to_absolute((p.x, p.y)) for p in path],
                        'path': path,
                        'path_length': path_length,
                        'goal_object': goal_obj,
                        'start': start,
                        'end': goal
                    }


        if best_result:
            path_finder.visualize_path(occ_map, best_result['path'],
                                       best_result['start'], best_result['end'])

            print(f"找到到达 {goal_object} 周围的路径，长度: {best_result['path_length']}")
            return best_result
        else:
            print(f"无法找到到达目标物体 {goal_object} 周围区域的路径")
            return None
